platform :ios, '10.0'
# use_frameworks

target 'manage' do
source 'https://github.com/CocoaPods/Specs.git'

# Pods
pod 'LCProgressHUD'
pod 'AFNetworking', '~> 4.0'
pod 'MJExtension', '~> 3.0.10'
pod 'FMDB', '~> 2.6'
pod 'MJRefresh', '~> 3.6.1'
pod 'Masonry'
pod 'Bugly'
pod 'WechatOpenSDK', '~> 1.8.7.1'
pod 'SDWebImage', '~> 3.7.5'
pod 'LBXScan', '~> 2.5'
pod 'LBXZBarSDK','~> 1.3'

#友盟
pod 'UMCCommon'
pod 'UMCPush'
pod 'UMCSecurityPlugins'


end

