//
//  Constant.h
//  framework
//
//  Created by 黄成实 on 2018/4/24.
//  Copyright © 2018年 黄成实. All rights reserved.
//

#import <Foundation/Foundation.h>

#define APP_NAME @"炭电"
#define MSG_WELCOME @"欢迎来到炭电"
#define MSG_SUCCESS @"请求成功"
#define MSG_ERROR @"网络错误码:%d"
#define MSG_CANCEL @"取消"
#define MSG_CONFIRM @"确定"
#define MSG_DELETE @"删除"
#define MSG_WARN @"警告"
#define MSG_PROMPT @"提示"
#define MSG_COMMIT @"提交"
#define MSG_SEARCH @"搜索"
#define MSG_MORE @"更多"
#define MSG_FINISH @"结束"
#define MSG_DATE_FORMAT_ZH @"yyyy年MM月dd日"
#define MSG_DATE_FORMAT_POINT @"yyyy.MM.dd"
#define MSG_DATE_FORMAT_ALL @"yyyy-MM-dd HH:mm:ss"
#define MSG_NET_ERROR @"网络连接失败，请检查您的网络"
#define MSG_INPUT @"请输入"
#define MSG_SAVE @"保存"
#define MSG_PIC_SAVE_SUCCESS @"图片保存成功"
#define MSG_PIC_SAVE_FAIL @"图片保存失败"
#define MSG_PHOTO_LIBRARY  @"账号图片已保存至您的相册"
#define MSG_UPDATE_SUCCESS @"修改成功"
#define MSG_UPDATE @"修改"
#define MSG_SELECT @"请选择"
#define MSG_YUAN @"元"
#define MSG_TIME_FORMAT @"yyyy-MM-dd HH:mm:ss"
#define MSG_EMPTY @""
#define MSG_BLANK @" "
#define MSG_ZERO @"0"

//分组
#define MSG_GROUP_CREATE @"创建分组"
#define MSG_GROUP_CREATE_SUCCESS @"创建分组成功"
#define MSG_GROUP_DETAIL @"查看分组"
#define MSG_GROUP_EDIT @"编辑分组"





#define MSG_INDUSTRYS @[@"宾馆/经济连锁酒店",@"网吧网咖",@"足疗按摩",@"洗浴/会所",@"星级酒店",@"中餐/茶馆",@"酒吧/KTV",@"美容行业",@"棋牌室",@"电影院",@"西餐咖啡厅",@"培训机构",@"医院",@"综合商场",@"其他"]

#define MSG_ADD_BK @"添加银行卡"
#define MSG_TX @"提现"
#define MSG_NOT_TX @"不可提现"
#define MSG_CAN_TX @"可提现"
#define MSG_TX_ACCOUNT @"提现账户名"
#define MSG_TX_CARD @"提现卡号"
#define MSG_TX_BK @"提现银行"
#define MSG_TX_TIP1 @"1.收益可提现时间: T+N。(可在“账户管理-账户详情”中查看结算周期)"
#define MSG_TX_TIP2 @"2. 如之前已经计提的用户订单发生退款，已经分给商户的利润在退款完成当日的收益中进行扣除"
#define MSG_TX_TIP3 @"3. 今日收益将在次日10点前统计汇总"
#define MSG_TX_ALL @"全部提现"
#define MSG_WD_EX @"预计3个工作日内，具体以银行到账时间为准。"
#define MSG_LIJI_TX @"立即提现"
#define MSG_NO_TX_DETAIL @"暂无提现明细"
#define MSG_NO_SY_DETAIL @"暂无收益"
#define MSG_SY_DETAIL @"收益明细"
#define MSG_TX_DETAIL @"提现明细"
#define MSG_NO_TX_MONEY @"暂无可提现金额"
#define MSG_NO_TX_FREEZE @"账户金额超过%.2f才可提现"
#define MSG_TX_FEE1 @"提现手续费为%.2f元/笔"
#define MSG_TX_FEE2 @"提现手续费为%.2f元/笔，实际到账%.2f元"
#define MSG_TX_FEE3 @"账户冻结金额为%.2f元，提现手续费为%.2f元/笔，实际到账%.2f元"
#define MSG_TX_TIPS @"提现手续费%.2f元/笔(银行收取)，支付手续费%.2f元（微信收取），代扣税%.2f元（税务局收取）\n实际到账%.2f元"
#define MSG_TX_MIN @"提现金额不可少于%.2f元"
#define MSG_TX_MAX @"提现金额不可大于%.2f元"
#define MSG_CAN_TX_MONEY @"可提现金额：%.2f元"
#define MSG_AUXILIARY_FREEZE @"账户冻结金额为%.2f元，"
#define MSG_AUXILIARY_AUXILIARY @"提现手续费%.2f元/笔，"
#define MSG_AUXILIARY_ACTURE @"实际到账%.2f元"
#define MSG_UPDATE_BANK_TIPS @"如需修改或删除银行卡，请联系平台或上级代理商"
//
#define MSG_BK_TYPE @"账户类型："
#define MSG_BK_DUIGONG_TYPE @"对公银行账户"
#define MSG_BK_GEREN_TYPE @"个人银行账户"
#define MSG_BK_DUIGONG @"银行对公账号："
#define MSG_BK_KAIHU @"开户银行："
#define MSG_BK_ZHIHANG @"支行名称："
#define MSG_BK_CARDNUM @"银行卡号："
//#define MSG_BK_WECHATID @"微信ID："
#define MSG_BK_ACCOUNT_NAME @"账户名称："
#define MSG_BK_KAIKAREN_NAME @"开卡人姓名："
#define MSG_BK_NICK_NAME @"微信昵称："
#define MSG_BK_KAIHU_ADDRESS @"开户所在地："
#define MSG_CARDNUM_BK @"银行卡号"
#define MSG_ACCOUNT_NAME @"账户名称"
#define MSG_TX_MONEY @"提现金额"
#define MSG_SX_MONEY @"提现手续费"
#define MSG_SX_PAY_MONEY @"支付手续费"
#define MSG_SHUI_MONEY @"代扣税"
#define MSG_SJDZ_MONEY @"实际到账"
#define MSG_APPLY_TIME @"申请时间"
#define MSG_LIUSHUI @"银行流水号"
#define MSG_TX_FAIL @"提现失败"
#define MSG_TX_FINISH @"提现完成"
#define MSG_TXING  @"提现中"
#define MSG_MAX_TX_MONEY @"超过最大可提现金额"
#define MSG_MAX_TX_WECHAT_MONEY @"超过微信单笔最大可提现金额"
#define MSG_TX_HISTORY  @"查看历史提现记录"
#define MSG_SELECT_BK @"请选择开户银行"
#define MSG_BLANK_KAIKAREN_NAME @"请输入开卡人姓名"
#define MSG_BLANK_BK_CARDNUM @"请输入银行卡号"
#define MSG_BLANK_BK_DUIGONG @"请输入银行对公账号"
#define MSG_BLANK_ZHIHANG @"请输入支行名称"
#define MSG_SELECT_KAIHU_ADDRESS @"请输入开户所在地"
#define MSG_KAIHU_BK @"开户银行"
#define MSG_BK_DETAIL @"银行卡信息"
#define MSG_NO_BK_DETAIL @"您当前还没有银行卡信息"
#define MSG_BLANK_TX_MONEY @"请输入提现金额"
#define MSG_BK_HANDING @"银行处理中"
#define MSG_DAOZHANG_SUCCESS @"到账成功"
#define MSG_WITHDRAW_INFO @"提现信息"
#define MSG_WITHDRAW_SELECT_STYLE @"选择提现方式"
#define MSG_WITHDRAW_STYLE @"提现方式"
#define MSG_WITHDRAW_NICKNAME @"微信昵称"
#define MSG_WITHDRAW_MONEY @"提现金额"

#define MSG_TEST_ID  @"bTIwMjEwNjA5MDAwMDM="
#define FONT_MIDDLE  @"PingFangSC-Medium"
#define FONT_REGULAR @"PingFangSC-Regular"
//菜单
#define MENU_ACTIVE @"激活设备"
#define MENU_ADD_MERCHANT @"添加商户"
#define MENU_ADD_AGENT @"添加代理商"
#define MENU_ADD_SALEMAN @"添加业务员"
#define MENU_ADD_CHAIN @"添加连锁门店"
#define MENU_RESET @"设备密码重置"
#define MENU_BIND_MERCHANT @"绑定商户"
#define MENU_TAXI @"出租车业务"


//tab
#define TAB_HOME @"首页"
#define TAB_CAPITAL @"收益"
#define TAB_ORDER @"订单"
#define TAB_MINE @"我的"

//个人
#define MENU_ACCOUNT @"账户信息"
#define MENU_BANK_INFO @"银行卡信息"
#define MENU_AGENT_MANAGE @"代理商管理"
#define MENU_UNBINDING @"设备解绑"
#define MENU_WHITELIST @"充电白名单"
#define MENU_MESSAGE @"消息中心"
#define MENU_SETTING @"APP设置"

#define MSG_WHITELIST_HISTORY @"白名单记录"

#define MSG_BK_WECHAT_TYPE @"微信零钱"
#define MSG_BIND_WECHAT_TITLE @"绑定微信零钱"
#define MSG_WITHDRAW_WECHAT @"您可以提现到微信零钱啦"
#define MSG_BIND_WECHAT_BTN @"点击绑定"
#define MSG_WITHDRAW_SELECT @"提现至"

#define MSG_WITHDRAW_GEREN @"个人账户（%@）"
#define MSG_WITHDRAW_DUIGONG @"对公账户（%@）"
#define MSG_WITHDRAW_BANKID_ERROR @"银行卡位数不正确"


#define MSG_WITHDRAW_RULE_BANK @"• 单笔提现金额不得低于%d元"
#define MSG_WITHDRAW_RULE_WECAHT @"• 单笔提现金额不得低于%d元，不得大于%d元"
#define MSG_WITHDRAW_RULE_TIME @"• 提现实时到账，异常情况不超过%d个工作日"
#define MSG_WITHDRAW_BANK_RULE_TIME @"• 预计%d个工作日内到账，具体以银行到账时间为准"
#define MSG_BANK_WITHDRAW_RULE @"%d元起提，%d个工作日到账"
#define MSG_WECHAT_WITHDRAW_RULE @"%d元起提，实时到账"

#define MSG_TITLE_ACCOUNT @"账户详情"
#define MSG_TITLE_ACHIEVE @"业绩明细"
#define MSG_TITLE_EDIT_CHAIN @"编辑连锁门店"
#define MSG_TITLE_EDIT_AGENT @"编辑代理商"
#define MSG_TITLE_EDIT_SUB_CHAIN @"编辑连锁门店分店"
#define MSG_TITLE_EDIT_MERCHANT @"编辑商户"
#define MSG_TITLE_AGENT_DETAIL @"代理商详情"
#define MSG_TITLE_MERCHANT_DETAIL @"商户详情"
#define MSG_TITLE_BIND_MERCHANT @"绑定商户"
#define MSG_TITLE_CAPITAL_DETAIL @"收益详情"
#define MSG_TITLE_HELP @"资金帮助"
#define MSG_TITLE_AGREEMENT @"用户协议"
#define MSG_TITLE_RESULT @"添加成功"
#define MSG_TITLE_MESSAGE @"消息"
#define MSG_TITLE_ORDER_DETAIL @"订单详情"
#define MSG_TITLE_REFUND @"退款"
#define MSG_TITLE_RESET_SUCCESS @"设备密码重置完成"
#define MSG_TITLE_ADD_DEVICE @"添加设备"
#define MSG_TITLE_SETTING @"APP设置"
#define MSG_TITLE_UPDATE_PSW @"修改密码"
#define MSG_TITLE_ABOUT @"关于我们"
#define MSG_TITLE_SCOPE @"使用范围"
#define MSG_TITLE_MERCHANT_BIND @"按商户解绑设备"
#define MSG_MERCHANT_BIND_SELECT @"选择需要解绑设备的商户"

#define MSG_AGENT_TYPE @"代理商类型"
#define MSG_AGENT_ACCOUNT @"代理商账号"
#define MSG_AGENT_NAME @"代理商名称"
#define MSG_AGENT_USER_NAME @"代理商姓名"
#define MSG_AGENT_PHONE @"代理商电话"
#define MSG_AGENT_INDUSTRY @"所属行业"
#define MSG_AGENT_SETTEMENT @"结算周期"
#define MSG_AGENT_PERCENT @"分润比例"
#define MSG_AGENT_SALEMAN @"关联业务员"
#define MSG_AGENT_CREATTIME @"账号创建日期"
#define MSG_AGENT_DEVICE_TOTAL @"设备总数"
#define MSG_AGENT_DEVICE_ACTIVE @"设备激活数"
#define MSG_AGENT_FREEZE @"冻结金额"
#define MSG_AGENT_ADDRESS @"区域位置"

#define MSG_AGENT_PROVINCE @"省代"
#define MSG_AGENT_CITY @"市代"
#define MSG_AGENT_AREA @"区/县代"
#define MSG_AGENT_CHIAN @"连锁门店"


#define MSG_ACCOUNT_TYPE @"账号类型"
#define MSG_SUB_CHAIN @"连锁门店分店"
#define MSG_MERCHANT @"商户"
#define MSG_MERCHANT_NAME @"商户名称"
#define MSG_MERCHANT_INDUSTRY @"所属行业"
#define MSG_MERCHANT_USER_NAME @"联系人姓名"
#define MSG_MERCHANT_PHONE @"联系人电话"
#define MSG_MERCHANT_SETTEMENT @"结算周期"
#define MSG_MERCHANT_PERCENT @"分润比例(绝对)"
#define MSG_MERCHANT_PERCENT_RELATIVE @"分润比例(相对)"
#define MSG_MERCHANT_PERCENT_REAL @"商户实际分润比例"
#define MSG_MERCHANT_SALEMAN @"关联业务员"
#define MSG_MERCHANT_CREATETIME @"账号创建日期"
#define MSG_MERCHANT_FREEZE @"冻结金额"
#define MSG_MERCHANT_DEVICE_TOTAL @"设备总数"
#define MSG_MERCHANT_DEVICE_ACTIVE @"设备激活数"
#define MSG_MERCHANT_ADDRESS @"区域位置"

#define MSG_MERCHANT_PROVINCE @"省代"
#define MSG_MERCHANT_CITY @"市代"
#define MSG_MERCHANT_AREA @"区/县代"
#define MSG_MERCHANT_CHIAN @"连锁门店"

#define MSG_SCALE_NUM @"第%@档"
#define MSG_TIME_PRICE @"%d小时%.2f元"

#define MSG_BIND_MERCHANT_SUCCESS @"商户绑定成功"
#define MSG_BIND_MERCHANT_CONTENT @"商户名称：%@\n商户联系人：%@"
#define MSG_RESULT_COPY_SUCCESS @"复制成功"
#define MSG_RESULT_CONTENT @"账号:%@\n密码:%@"
#define MSG_RESULT_COPY_ACCOUNT @"请先点击复制账号密码"
#define MSG_MERCHANT_ADD_SUCCESS @"商户账号添加成功"
#define MSG_MERCHANT_BIND_TIPS (IS_YELLOW_SKIN ? @"请及时将商户账号绑定到“炭商家版”微信公众号" : @"请及时将商户账号绑定到“小红电商家版”微信公众号")
#define MSG_MERCHANT_BIND_STEP @"绑定步骤"
#define MSG_MERCHANT_BIND_STEP1 (IS_YELLOW_SKIN ? @"1. 请通知商户关注微信公众号“炭电商家版”，获得商户二维码；" : @"1. 请通知商户关注微信公众号“小红电商家版”，获得商户二维码；" )
#define MSG_MERCHANT_BIND_STEP2 (IS_YELLOW_SKIN ? @"2. 请代理商或业务员登录炭电-代理商版App，扫描商户二维码，完成商户账号绑定" : @"2. 请代理商或业务员登录小红电-代理商版App，扫描商户二维码，完成商户账号绑定" )
#define MSG_REFUND_SUCCESS @"退款成功"

#define MSG_SCAN_LUNCHER @"相机启动中"
#define MSG_SCAN_ACTIVE_DEVICE @"扫码激活设备"
#define MSG_SCAN_HAS_ACTIVE @"已激活设备"
#define MSG_SCAN_QRCODE @"请扫描商户二维码"
#define MSG_SCAN_RESET_QRCODE @"请扫描需要密码重置的设备二维码"
#define MSG_SCAN_HAS_ADD @"已添加设备"
#define MSG_SCAN_OPEN_LIGHT @"轻触打开电筒"
#define MSG_SCAN_CLOSE_LIGHT @"轻触关闭电筒"
#define MSG_SCAN_FAIL @"二维码识别失败，请检查您的网络"
#define MSG_SCAN_TIPS @"请扫描正确的商户二维码"
#define MSG_SCAN_FAIL_ERROR_QRCODE @"无法识别二维码"
#define MSG_SCAN_FAIL_DEVICE_NO_EXIT @"该设备未激活/不存在"



#define MSG_DEVICE_ACTIVE_SUCCESS @"设备激活成功"
#define MSG_DEVICE_ADD_SUCCESS @"添加设备成功"
#define MSG_CONFIRM_EXIT @"确认退出吗"
#define MSG_UPDATE_PSW_SUCCESS @"密码修改成功"

#define MSG_WHITELIST_OPEN @"启用"
#define MSG_WHITELIST_CLOSE @"禁用"
#define MSG_WHITELIST_OPEN_CONFIRM @"请确认是否启用该用户为白名单"
#define MSG_WHITELIST_CLOSE_CONFIRM @"请确认是否禁用该用户为白名单"
#define MSG_WHITELIST_COPY @"复制白名单"
#define MSG_WHITELIST_COPY_CONFIRM @"新的白名单客户将复制此客户的使用范围"
#define MSG_SCOPE_SELECT @"请选择一个范围"
#define MSG_GROUP_CREATE @"创建分组"
#define MSG_TAXI_TITLE1 @"1、什么是出租⻋业务"
#define MSG_TAXI_TITLE2 @"2、出租车业务的开展流程"
#define MSG_TAXI_CONTENT @"是指在出租车铺设充电设备，供乘客使用。"
#define MSG_TAXI_STEP_TITLE1 @"第⼀步:创建分组"
#define MSG_TAXI_STEP_TITLE2 @"第⼆步:添加设备至分组"
#define MSG_TAXI_STEP_TITLE3 @"第三步:出售设备给司机"
#define MSG_TAXI_STEP_CONTENT1 @"可创建多个分组，不同的组设置不同的充电计费规则、司机分润比例等"
#define MSG_TAXI_STEP_CONTENT2 @"设备最终使用时，将按照所在分组的设备计费规则、分润⽐例等进⾏计费、分润。"
#define MSG_TAXI_STEP_CONTENT3 @"司机通过扫描设备⼆维码，注册账户并激活设备。激活完成后，乘客就可以使⽤了。"
#define MSG_TAXI_PERCENT @"司机分润比例"
#define MSG_TAXI_RULE @"设备计费规则"
#define MSG_TAXI_SALEMAN @"关联业务员"
#define MSG_TAXI_DEVICE_TOTAL @"设备总数"
#define MSG_TAXI_ACTIVE_TOTAL @"激活设备"
#define MSG_TAXI_DRIVE_TOTAL @"司机数量"

#define MSG_GROUP_NAME @"分组名称（必填）"
#define MSG_GROUP_NAME_PLACEHOLDER @"可根据地域命名"
#define MSG_GROUP_SALENAME @"关联业务员(必填)"
#define MSG_GROUP_RULE @"设备计费规则（必填）"
#define MSG_GROUP_PERCENT @"司机分润比例（必填）"
#define MSG_GROUP_DEFAULT_UNIT @"元/2小时"
#define MSG_GROUP_UNIT @"元/%d小时"
#define MSG_GROUP_FREEZE @"设备冻结款（必填）"
#define MSG_GROUP_FREEZE_TIPS @"设备冻结款是指从司机账户中冻结的设备成本费用，后期将转入代理商账户。如无需冻结，可设为0"
#define MSG_GROUP_PRE_SALENAME @"售前联系人姓名"
#define MSG_GROUP_PRE_PHONE @"售前联系电话（必填）"
#define MSG_GROUP_ADDRESS_DETAIL @"详细地址"
#define MSG_GROUP_ADDRESS_DETAIL_PLACEHOLDER @"请输入详细地址"
#define MSG_GROUP_PRE_TIPS @"售前信息⽤于对接司机的售前咨询，例如购买咨询"
#define MSG_GROUP_PRE_ADDRESS @"售前联系地址"
#define MSG_GROUP_SELECT_CITY @"请选择省/市/区"
#define MSG_PROVINCE_CITY_DISTRICT @"省/市/区"
#define MSG_ADDRESS_DETAIL @"详细地址"
#define MSG_GROUP_AFTER_SALENAME @"售后联系人姓名"
#define MSG_GROUP_AFTER_PHONE @"售后联系电话（必填）"
#define MSG_GROUP_AFTER_TIPS @"售后信息用于对接司机的售后问题，例如更换设备"
#define MSG_GROUP_AFTER_ADDRESS @"售后联系地址"

#define MSG_PROFIT_TOTAL @"您的利润总比例为：%.2f%%，剩余比例：%.2f%%"
#define MSG_PROFIT_RANGE1 @"您的利润总比例为："
#define MSG_PROFIT_RANGE2 @"，剩余比例："


#define MSG_SCAN_BIND @"扫码解绑"
#define MSG_MERCHANT_BIND @"按照商户解绑"
#define MSG_SCAN_BIND_CONTENT @"扫码设备二维码，解绑设备"
#define MSG_MERCHANT_BIND_CONTENT @"选择商户，一键批量解绑"
#define MSG_UNBIND_MERCHANT_TIPS @"设备解绑后，将恢复成未绑定未激活状态，设备将无法使用，\n请谨慎操作！"
#define MSG_UNBIND_DEVICE_SN @"设备编号"
#define MSG_UNBIND_BTN @"设备解绑"
#define MSG_SELECT_ACTIVE_MERCHANT @"选择激活设备的商户"
#define MSG_UNBIND_MERCHANTID @"商户编号"
#define MSG_UNBIND_CONTACT @"联系人姓名"
#define MSG_UNBIND_TOTAL @"设备总数"
#define MSG_UNBIND_ALL_BTN @"批量解绑"
#define MSG_UNBIND_NO_ACTIVE_DEVICE @"无激活设备，不需要解绑"
#define MSG_UNBIND_SUCCESS @"解绑成功"
#define MSG_UNBIND_SUCCESS_COUNT @"解绑成功设备%d个"
#define MSG_UNBIND_FAIL @"解绑失败"
#define MSG_UNBIND_FAIL_COUNT @"解绑失败设备%d个"
#define MSG_UNBIND_BACK_HOME @"返回首页"
#define MSG_INVITE @"炭邀请您免费充电"
#define MSG_NO_ORDER @"暂无订单"

#define MSG_LOCATION @"位置"
#define MSG_CONTACTPHONE_TIPS @"手机号码填写错误，商户将无法提现"
#define MSG_CONTACTPHONE_TIPS2 @"用来作为账号密码找回"
